<?php
session_start();
$con=mysqli_connect("localhost","root","","online_education")or die("connection error");
$id=$_GET['id'];
$_SESSION['c_id']=$id;
$sql="SELECT * FROM `tbl_course` WHERE c_id=$id;
";
$qry=mysqli_query($con,$sql);
$row=mysqli_fetch_assoc($qry);
$pr=$row['c_price'];
$sub=$row['c_title'];
$name=$_SESSION['name'];
$email=$_SESSION['email'];
$sql1="SELECT * FROM `tbl_reg` WHERE s_email='$email';";
$qry1=mysqli_query($con,$sql1);
$row1=mysqli_fetch_assoc($qry1);
$mob=$row1['s_phone'];
$sqlnew="INSERT INTO `tbl_payment_info` (`s_name`, `s_sub`, `s_email`, `mob_no`, `c_price`) VALUES ('$name', '$sub', '$email', '$mob', '$pr');";
$qrynew=mysqli_query($con,$sqlnew);

 $apiKey = "rzp_test_Wi972bG7df7ltY";

?>

<script src="https://code.jquery.com/jquery-3.5.0.js"></script>



<form action="success.php" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $apiKey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php echo $row['c_price'] * 100;?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"//You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-id="<?php echo 'OID'.rand(10,100).'END';?>"//Replace with the order_id generated by you in the backend.
    data-buttontext="CLICK ME TO DONATION"
    data-name="Ishita Sharma"
    data-description="DONATE!"
    data-prefill.name="<?php echo 'paresh';?>"
    data-prefill.email="<?php echo $_POST['email'];?>"
    data-prefill.contact="<?php echo $_POST['mobile'];?>"
    data-theme.color="#F37254"
></script>
<input type="hidden" custom="Hidden Element" name="hidden">
</form>


<style type="text/css">
    .razorpay-payment-button{
        display: none;
    }
</style>

<script type="text/javascript">
    $(document).ready(function(){
        $('.razorpay-payment-button').click();
    });
</script>